/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blueteam_testndk_utils_JniUtils */

#ifndef _Included_com_blueteam_testndk_utils_JniUtils
#define _Included_com_blueteam_testndk_utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blueteam_testndk_utils_JniUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_blueteam_testndk_utils_JniUtils_getStringFromC
  (JNIEnv *env, jobject obj){
    jclass StringUtils =(*env)->FindClass(env,"com/blueteam/testndk/utils/StringUtils");
    jobject mStringUtils;
    jmethodID construction_id = (*env)->GetMethodID(env,StringUtils,"<init>","()V");
    mStringUtils = (*env)->NewObject(env,StringUtils,construction_id);
    jmethodID getJavaStrs =(*env)->GetMethodID(env,StringUtils,"getJavaStrs","()Ljava/lang/String;");
     jstring native_desc = (jstring)(*env)->CallObjectMethod(env,mStringUtils,getJavaStrs);
//    return (*env)->NewStringUTF(env, "hello java from c");
    return native_desc;
};


#ifdef __cplusplus
}
#endif
#endif//
// Created by Administrator on 2016/7/11.
//

